JohannesDeml/UnityWebGL-LoadingTest

ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2022.2.9f1-webgl2
* https://deml.io/experiments/unity-webgl/2022.2.9f1-webgl1
=> [Automated workflow] upgrade-unity from 2022.2.7f1 to 2022.2.9f1

ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2021.3.20f1-webgl2
* https://deml.io/experiments/unity-webgl/2021.3.20f1-webgl1
=> [Automated workflow] upgrade-unity from 2021.3.18f1 to 2021.3.20f1

ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2020.3.46f1-webgl2
* https://deml.io/experiments/unity-webgl/2020.3.46f1-webgl1
=> [Automated workflow] upgrade-unity from 2020.3.44f1 to 2020.3.46f1

ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2022.2.12f1-webgl2
* https://deml.io/experiments/unity-webgl/2022.2.12f1-webgl1
=> [Automated workflow] upgrade-unity from 2022.2.9f1 to 2022.2.12f1

ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2022.2.12f1-urp-webgl2
* https://deml.io/experiments/unity-webgl/2022.2.12f1-urp-webgl1
=> [Automated workflow] upgrade-unity from 2022.2.9f1 to 2022.2.12f1-urp

ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2021.3.21f1-urp-webgl2
* https://deml.io/experiments/unity-webgl/2021.3.21f1-urp-webgl1
=> [Automated workflow] upgrade-unity from 2021.3.20f1 to 2021.3.21f1-urp

ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2021.3.21f1-webgl2
* https://deml.io/experiments/unity-webgl/2021.3.21f1-webgl1
=> [Automated workflow] upgrade-unity from 2021.3.20f1 to 2021.3.21f1

ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2022.2.18f1-webgl2
* https://deml.io/experiments/unity-webgl/2022.2.18f1-webgl1
=> [Automated workflow] upgrade-unity from 2022.2.17f1 to 2022.2.18f1

ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2021.3.25f1-webgl2
* https://deml.io/experiments/unity-webgl/2021.3.25f1-webgl1
=> [Automated workflow] upgrade-unity from 2021.3.24f1 to 2021.3.25f1

ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2021.3.25f1-urp-webgl2
* https://deml.io/experiments/unity-webgl/2021.3.25f1-urp-webgl1
=> [Automated workflow] upgrade-unity from 2021.3.24f1 to 2021.3.25f1-urp

ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2022.3.1f1-webgl2
* https://deml.io/experiments/unity-webgl/2022.3.1f1-webgl1
=> [Automated workflow] upgrade-unity from 2022.3.0f1 to 2022.3.1f1

ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2022.3.3f1-webgl2
* https://deml.io/experiments/unity-webgl/2022.3.3f1-webgl1
=> [Automated workflow] upgrade-unity from 2022.3.2f1 to 2022.3.3f1

ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2022.3.15f1-webgl2
* https://deml.io/experiments/unity-webgl/2022.3.15f1-webgl1
=> [Automated workflow] upgrade-unity from 2022.3.14f1 to 2022.3.15f1

ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2022.3.16f1-urp-webgl2
* https://deml.io/experiments/unity-webgl/2022.3.16f1-urp-webgl1
=> [Automated workflow] upgrade-unity from 2022.3.15f1 to 2022.3.16f1-urp

ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2022.3.16f1-webgl2
* https://deml.io/experiments/unity-webgl/2022.3.16f1-webgl1
=> [Automated workflow] upgrade-unity from 2022.3.15f1 to 2022.3.16f1

ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2023.2.7f1-webgl2
* https://deml.io/experiments/unity-webgl/2023.2.7f1-webgl1
=> [Automated workflow] upgrade-unity from 2023.2.3f1 to 2023.2.7f1

ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2023.2.9f1-webgl2
* https://deml.io/experiments/unity-webgl/2023.2.9f1-webgl1
=> [Automated workflow] upgrade-unity from 2023.2.7f1 to 2023.2.9f1

Assets/Prefabs/RigidbodyCube.prefab, Assets/Scenes/Main.unity, Packages/manifest.json, Packages/packages-lock.json
* https://deml.io/experiments/unity-webgl/2022.1.24f1-urp-webgl2
* https://deml.io/experiments/unity-webgl/2022.1.24f1-urp-webgl1
=> [Automated workflow] upgrade-unity from 2022.1.24f1 to 2022.1.24f1-urp

Packages/manifest.json, Packages/packages-lock.json, ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/6000.0.2f1-webgl2
* https://deml.io/experiments/unity-webgl/6000.0.2f1-webgl1
=> [Automated workflow] upgrade-unity from 6000.0.0f1 to 6000.0.2f1

ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/6000.0.9f1-webgl2
* https://deml.io/experiments/unity-webgl/6000.0.9f1-webgl1
=> [Automated workflow] upgrade-unity from 6000.0.8f1 to 6000.0.9f1

ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2022.3.42f1-webgl2
* https://deml.io/experiments/unity-webgl/2022.3.42f1-webgl1
=> [Automated workflow] upgrade-unity from 2022.3.36f1 to 2022.3.42f1

Packages/manifest.json, Packages/packages-lock.json, ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/6000.0.19f1-webgl2
* https://deml.io/experiments/unity-webgl/6000.0.19f1-webgl1
=> [Automated workflow] upgrade-unity from 6000.0.16f1 to 6000.0.19f1

Assets/UniversalRenderPipelineGlobalSettings.asset, Packages/manifest.json, Packages/packages-lock.json, ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/6000.0.19f1-urp-webgl2
* https://deml.io/experiments/unity-webgl/6000.0.19f1-urp-webgl1
=> [Automated workflow] upgrade-unity from 6000.0.9f1 to 6000.0.19f1-urp

ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2021.3.45f1-webgl2
* https://deml.io/experiments/unity-webgl/2021.3.45f1-webgl1
=> [Automated workflow] upgrade-unity from 2021.3.43f1 to 2021.3.45f1

ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/6000.0.23f1-webgl2
* https://deml.io/experiments/unity-webgl/6000.0.23f1-webgl1
=> [Automated workflow] upgrade-unity from 6000.0.19f1 to 6000.0.23f1

Packages/manifest.json, Packages/packages-lock.json, ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/6000.0.23f1-urp-webgl2
* https://deml.io/experiments/unity-webgl/6000.0.23f1-urp-webgl1
=> [Automated workflow] upgrade-unity from 6000.0.19f1 to 6000.0.23f1-urp

ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/6000.0.27f1-webgl2
* https://deml.io/experiments/unity-webgl/6000.0.27f1-webgl1
=> [Automated workflow] upgrade-unity from 6000.0.25f1 to 6000.0.27f1

ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/6000.0.27f1-urp-webgl2
* https://deml.io/experiments/unity-webgl/6000.0.27f1-urp-webgl1
=> [Automated workflow] upgrade-unity from 6000.0.25f1 to 6000.0.27f1-urp

ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/6000.0.31f1-urp-webgl2
* https://deml.io/experiments/unity-webgl/6000.0.31f1-urp-webgl1
=> [Automated workflow] upgrade-unity from 6000.0.27f1 to 6000.0.31f1-urp

ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2022.3.54f1-webgl2
* https://deml.io/experiments/unity-webgl/2022.3.54f1-webgl1
=> [Automated workflow] upgrade-unity from 2022.3.52f1 to 2022.3.54f1

ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2022.3.54f1-urp-webgl2
* https://deml.io/experiments/unity-webgl/2022.3.54f1-urp-webgl1
=> [Automated workflow] upgrade-unity from 2022.3.52f1 to 2022.3.54f1-urp

ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/6000.0.32f1-webgl2
* https://deml.io/experiments/unity-webgl/6000.0.32f1-webgl1
=> [Automated workflow] upgrade-unity from 6000.0.31f1 to 6000.0.32f1

ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/6000.0.33f1-webgl2
* https://deml.io/experiments/unity-webgl/6000.0.33f1-webgl1
=> [Automated workflow] upgrade-unity from 6000.0.32f1 to 6000.0.33f1

ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/6000.0.34f1-webgl2
* https://deml.io/experiments/unity-webgl/6000.0.34f1-webgl1
=> [Automated workflow] upgrade-unity from 6000.0.33f1 to 6000.0.34f1

Assets/UniversalRenderPipelineGlobalSettings.asset, ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/6000.0.33f1-urp-webgl2
* https://deml.io/experiments/unity-webgl/6000.0.33f1-urp-webgl1
=> [Automated workflow] upgrade-unity from 6000.0.32f1-urp to 6000.0.33f1-urp

ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/6000.0.34f1-urp-webgl2
* https://deml.io/experiments/unity-webgl/6000.0.34f1-urp-webgl1
=> [Automated workflow] upgrade-unity from 6000.0.33f1-urp to 6000.0.34f1-urp

ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2022.3.56f1-webgl2
* https://deml.io/experiments/unity-webgl/2022.3.56f1-webgl1
=> [Automated workflow] upgrade-unity from 2022.3.54f1 to 2022.3.56f1

Packages/manifest.json, Packages/packages-lock.json, ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/6000.0.37f1-webgl2
* https://deml.io/experiments/unity-webgl/6000.0.37f1-webgl1
=> [Automated workflow] upgrade-unity from 6000.0.34f1 to 6000.0.37f1

Packages/manifest.json, Packages/packages-lock.json, ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/6000.0.37f1-urp-webgl2
* https://deml.io/experiments/unity-webgl/6000.0.37f1-urp-webgl1
=> [Automated workflow] upgrade-unity from 6000.0.34f1-urp to 6000.0.37f1-urp

ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/6000.0.40f1-webgl2
* https://deml.io/experiments/unity-webgl/6000.0.40f1-webgl1
=> [Automated workflow] upgrade-unity from 6000.0.37f1 to 6000.0.40f1

Packages/manifest.json, Packages/packages-lock.json, ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/6000.0.42f1-urp-webgl2
* https://deml.io/experiments/unity-webgl/6000.0.42f1-urp-webgl1
=> [Automated workflow] upgrade-unity from 6000.0.40f1-urp to 6000.0.42f1-urp

ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/6000.1.1f1-webgl2
* https://deml.io/experiments/unity-webgl/6000.1.1f1-webgl1
=> [Automated workflow] upgrade-unity from 6000.1.0f1 to 6000.1.1f1
