JohannesDeml/UnityWebGL-LoadingTest

- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2022.2.9f1-urp-webgl2
* https://deml.io/experiments/unity-webgl/2022.2.9f1-urp-webgl1
> [Automated workflow] upgrade-unity from 2022.2.7f1 to 2022.2.9f1-urp

- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2021.3.20f1-urp-webgl2
* https://deml.io/experiments/unity-webgl/2021.3.20f1-urp-webgl1
> [Automated workflow] upgrade-unity from 2021.3.18f1 to 2021.3.20f1-urp

- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2020.3.46f1-urp-webgl2
* https://deml.io/experiments/unity-webgl/2020.3.46f1-urp-webgl1
> [Automated workflow] upgrade-unity from 2020.3.44f1 to 2020.3.46f1-urp

- Assets/WebGLTemplates/Release/pretty-console.js.meta
- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2022.2.13f1-urp-webgl2
* https://deml.io/experiments/unity-webgl/2022.2.13f1-urp-webgl1
> [Automated workflow] upgrade-unity from 2022.2.12f1 to 2022.2.13f1-urp

- Assets/WebGLTemplates/Release/pretty-console.js.meta
- ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2022.2.13f1-webgl2
* https://deml.io/experiments/unity-webgl/2022.2.13f1-webgl1
> [Automated workflow] upgrade-unity from 2022.2.12f1 to 2022.2.13f1

- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2021.3.22f1-urp-webgl2
* https://deml.io/experiments/unity-webgl/2021.3.22f1-urp-webgl1
> [Automated workflow] upgrade-unity from 2021.3.21f1 to 2021.3.22f1-urp

- Assets/WebGLTemplates/Develop/index.html
- Assets/WebGLTemplates/Release/index.html
- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2022.2.14f1-urp-webgl2
* https://deml.io/experiments/unity-webgl/2022.2.14f1-urp-webgl1
> [Automated workflow] upgrade-unity from 2022.2.13f1 to 2022.2.14f1-urp

- Assets/URP/UniversalRenderPipelineAsset_Renderer.asset
- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2022.2.15f1-urp-webgl2
* https://deml.io/experiments/unity-webgl/2022.2.15f1-urp-webgl1
> [Automated workflow] upgrade-unity from 2022.2.14f1 to 2022.2.15f1-urp

- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2020.3.47f1-webgl2
* https://deml.io/experiments/unity-webgl/2020.3.47f1-webgl1
> [Automated workflow] upgrade-unity from 2020.3.46f1 to 2020.3.47f1

- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2022.2.15f1-webgl2
* https://deml.io/experiments/unity-webgl/2022.2.15f1-webgl1
> [Automated workflow] upgrade-unity from 2022.2.14f1 to 2022.2.15f1

- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2020.3.47f1-urp-webgl2
* https://deml.io/experiments/unity-webgl/2020.3.47f1-urp-webgl1
> [Automated workflow] upgrade-unity from 2020.3.46f1 to 2020.3.47f1-urp

- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2022.2.17f1-urp-webgl2
* https://deml.io/experiments/unity-webgl/2022.2.17f1-urp-webgl1
> [Automated workflow] upgrade-unity from 2022.2.15f1 to 2022.2.17f1-urp

- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2021.3.24f1-urp-webgl2
* https://deml.io/experiments/unity-webgl/2021.3.24f1-urp-webgl1
> [Automated workflow] upgrade-unity from 2021.3.22f1 to 2021.3.24f1-urp

- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2021.3.24f1-webgl2
* https://deml.io/experiments/unity-webgl/2021.3.24f1-webgl1
> [Automated workflow] upgrade-unity from 2021.3.22f1 to 2021.3.24f1

- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2022.2.17f1-webgl2
* https://deml.io/experiments/unity-webgl/2022.2.17f1-webgl1
> [Automated workflow] upgrade-unity from 2022.2.15f1 to 2022.2.17f1

- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2022.2.18f1-urp-webgl2
* https://deml.io/experiments/unity-webgl/2022.2.18f1-urp-webgl1
> [Automated workflow] upgrade-unity from 2022.2.17f1 to 2022.2.18f1-urp

- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2020.3.48f1-urp-webgl2
* https://deml.io/experiments/unity-webgl/2020.3.48f1-urp-webgl1
> [Automated workflow] upgrade-unity from 2020.3.47f1 to 2020.3.48f1-urp

- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2020.3.48f1-webgl2
* https://deml.io/experiments/unity-webgl/2020.3.48f1-webgl1
> [Automated workflow] upgrade-unity from 2020.3.47f1 to 2020.3.48f1

- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2022.3.1f1-urp-webgl2
* https://deml.io/experiments/unity-webgl/2022.3.1f1-urp-webgl1
> [Automated workflow] upgrade-unity from 2022.3.0f1 to 2022.3.1f1-urp

- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2022.3.2f1-webgl2
* https://deml.io/experiments/unity-webgl/2022.3.2f1-webgl1
> [Automated workflow] upgrade-unity from 2022.3.1f1 to 2022.3.2f1

- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2022.3.2f1-urp-webgl2
* https://deml.io/experiments/unity-webgl/2022.3.2f1-urp-webgl1
> [Automated workflow] upgrade-unity from 2022.3.1f1 to 2022.3.2f1-urp

- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2022.3.3f1-urp-webgl2
* https://deml.io/experiments/unity-webgl/2022.3.3f1-urp-webgl1
> [Automated workflow] upgrade-unity from 2022.3.2f1 to 2022.3.3f1-urp

- Assets/URP/UniversalRenderPipelineAsset_Renderer.asset
- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2023.1.1f1-urp-webgl2
* https://deml.io/experiments/unity-webgl/2023.1.1f1-urp-webgl1
> [Automated workflow] upgrade-unity from 2023.1.0f1 to 2023.1.1f1-urp

- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2023.1.5f1-urp-webgl2
* https://deml.io/experiments/unity-webgl/2023.1.5f1-urp-webgl1
> [Automated workflow] upgrade-unity from 2023.1.1f1 to 2023.1.5f1-urp

- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2023.1.5f1-webgl2
* https://deml.io/experiments/unity-webgl/2023.1.5f1-webgl1
> [Automated workflow] upgrade-unity from 2023.1.1f1 to 2023.1.5f1

- Assets/URP/UniversalRenderPipelineAsset_Renderer.asset
- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2022.3.7f1-urp-webgl2
* https://deml.io/experiments/unity-webgl/2022.3.7f1-urp-webgl1
> [Automated workflow] upgrade-unity from 2022.3.3f1 to 2022.3.7f1-urp

- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2022.3.7f1-webgl2
* https://deml.io/experiments/unity-webgl/2022.3.7f1-webgl1
> [Automated workflow] upgrade-unity from 2022.3.3f1 to 2022.3.7f1

- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2022.3.10f1-webgl2
* https://deml.io/experiments/unity-webgl/2022.3.10f1-webgl1
> [Automated workflow] upgrade-unity from 2022.3.7f1 to 2022.3.10f1

- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2021.3.31f1-urp-webgl2
* https://deml.io/experiments/unity-webgl/2021.3.31f1-urp-webgl1
> [Automated workflow] upgrade-unity from 2021.3.25f1 to 2021.3.31f1-urp

- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2021.3.31f1-webgl2
* https://deml.io/experiments/unity-webgl/2021.3.31f1-webgl1
> [Automated workflow] upgrade-unity from 2021.3.25f1 to 2021.3.31f1

- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2022.3.10f1-urp-webgl2
* https://deml.io/experiments/unity-webgl/2022.3.10f1-urp-webgl1
> [Automated workflow] upgrade-unity from 2022.3.7f1 to 2022.3.10f1-urp

- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2023.1.16f1-webgl2
* https://deml.io/experiments/unity-webgl/2023.1.16f1-webgl1
> [Automated workflow] upgrade-unity from 2023.1.5f1 to 2023.1.16f1

- Packages/manifest.json
- Packages/packages-lock.json
* https://deml.io/experiments/unity-webgl/2020.3.48f1-urp-webgl2
* https://deml.io/experiments/unity-webgl/2020.3.48f1-urp-webgl1
> [Automated workflow] upgrade-unity from 2020.3.48f1 to 2020.3.48f1-urp

- Packages/manifest.json
- Packages/packages-lock.json
* https://deml.io/experiments/unity-webgl/2020.3.48f1-webgl2
* https://deml.io/experiments/unity-webgl/2020.3.48f1-webgl1
> [Automated workflow] upgrade-unity from 2020.3.48f1 to 2020.3.48f1

- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2023.1.17f1-webgl2
* https://deml.io/experiments/unity-webgl/2023.1.17f1-webgl1
> [Automated workflow] upgrade-unity from 2023.1.16f1 to 2023.1.17f1

- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2021.3.33f1-webgl2
* https://deml.io/experiments/unity-webgl/2021.3.33f1-webgl1
> [Automated workflow] upgrade-unity from 2021.3.31f1 to 2021.3.33f1

- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2023.1.20f1-webgl2
* https://deml.io/experiments/unity-webgl/2023.1.20f1-webgl1
> [Automated workflow] upgrade-unity from 2023.1.17f1 to 2023.1.20f1

- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2023.1.20f1-urp-webgl2
* https://deml.io/experiments/unity-webgl/2023.1.20f1-urp-webgl1
> [Automated workflow] upgrade-unity from 2023.1.18f1 to 2023.1.20f1-urp

- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2022.3.14f1-webgl2
* https://deml.io/experiments/unity-webgl/2022.3.14f1-webgl1
> [Automated workflow] upgrade-unity from 2022.3.10f1 to 2022.3.14f1

- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
- ProjectSettings/ShaderGraphSettings.asset
* https://deml.io/experiments/unity-webgl/2022.3.14f1-urp-webgl2
* https://deml.io/experiments/unity-webgl/2022.3.14f1-urp-webgl1
> [Automated workflow] upgrade-unity from 2022.3.10f1 to 2022.3.14f1-urp

- Packages/manifest.json
- Packages/packages-lock.json
* https://deml.io/experiments/unity-webgl/2022.1.24f1-webgl2
* https://deml.io/experiments/unity-webgl/2022.1.24f1-webgl1
> [Automated workflow] upgrade-unity from 2022.1.24f1 to 2022.1.24f1

- Packages/manifest.json
- Packages/packages-lock.json
* https://deml.io/experiments/unity-webgl/2022.1.24f1-urp-webgl2
* https://deml.io/experiments/unity-webgl/2022.1.24f1-urp-webgl1
> [Automated workflow] upgrade-unity from 2022.1.24f1 to 2022.1.24f1-urp

- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2022.3.15f1-urp-webgl2
* https://deml.io/experiments/unity-webgl/2022.3.15f1-urp-webgl1
> [Automated workflow] upgrade-unity from 2022.3.14f1 to 2022.3.15f1-urp

- Assets/URP/UniversalRenderPipelineAsset.asset
- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2023.2.7f1-urp-webgl2
* https://deml.io/experiments/unity-webgl/2023.2.7f1-urp-webgl1
> [Automated workflow] upgrade-unity from 2023.2.3f1 to 2023.2.7f1-urp

- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2022.3.19f1-webgl2
* https://deml.io/experiments/unity-webgl/2022.3.19f1-webgl1
> [Automated workflow] upgrade-unity from 2022.3.16f1 to 2022.3.19f1

- Packages/manifest.json
- Packages/packages-lock.json
* https://deml.io/experiments/unity-webgl/2023.1.20f1-webgl2
* https://deml.io/experiments/unity-webgl/2023.1.20f1-webgl1
> [Automated workflow] upgrade-unity from 2023.1.20f1 to 2023.1.20f1

- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2023.2.10f1-urp-webgl2
* https://deml.io/experiments/unity-webgl/2023.2.10f1-urp-webgl1
> [Automated workflow] upgrade-unity from 2023.2.7f1 to 2023.2.10f1-urp

- Packages/manifest.json
- Packages/packages-lock.json
* https://deml.io/experiments/unity-webgl/2023.1.20f1-urp-webgl2
* https://deml.io/experiments/unity-webgl/2023.1.20f1-urp-webgl1
> [Automated workflow] upgrade-unity from 2023.1.20f1 to 2023.1.20f1-urp

- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2023.2.10f1-webgl2
* https://deml.io/experiments/unity-webgl/2023.2.10f1-webgl1
> [Automated workflow] upgrade-unity from 2023.2.9f1 to 2023.2.10f1

- Packages/manifest.json
- Packages/packages-lock.json
* https://deml.io/experiments/unity-webgl/2021.3.35f1-urp-webgl2
* https://deml.io/experiments/unity-webgl/2021.3.35f1-urp-webgl1
> [Automated workflow] upgrade-unity from 2021.3.35f1 to 2021.3.35f1-urp

- Assets/Scripts/Editor/UnityPackageScripts.cs
- Packages/manifest.json
- Packages/packages-lock.json
* https://deml.io/experiments/unity-webgl/2022.2.18f1-urp-webgl2
* https://deml.io/experiments/unity-webgl/2022.2.18f1-urp-webgl1
> [Automated workflow] upgrade-unity from 2022.2.18f1 to 2022.2.18f1-urp

- Assets/Scripts/Editor/UnityPackageScripts.cs
- Packages/manifest.json
- Packages/packages-lock.json
* https://deml.io/experiments/unity-webgl/2022.2.18f1-webgl2
* https://deml.io/experiments/unity-webgl/2022.2.18f1-webgl1
> [Automated workflow] upgrade-unity from 2022.2.18f1 to 2022.2.18f1

- Packages/manifest.json
- Packages/packages-lock.json
* https://deml.io/experiments/unity-webgl/2021.3.35f1-webgl2
* https://deml.io/experiments/unity-webgl/2021.3.35f1-webgl1
> [Automated workflow] upgrade-unity from 2021.3.35f1 to 2021.3.35f1

- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2022.3.24f1-webgl2
* https://deml.io/experiments/unity-webgl/2022.3.24f1-webgl1
> [Automated workflow] upgrade-unity from 2022.3.20f1 to 2022.3.24f1

- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2023.2.18f1-webgl2
* https://deml.io/experiments/unity-webgl/2023.2.18f1-webgl1
> [Automated workflow] upgrade-unity from 2023.2.10f1 to 2023.2.18f1

- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2022.3.24f1-urp-webgl2
* https://deml.io/experiments/unity-webgl/2022.3.24f1-urp-webgl1
> [Automated workflow] upgrade-unity from 2022.3.20f1 to 2022.3.24f1-urp

- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2023.2.18f1-urp-webgl2
* https://deml.io/experiments/unity-webgl/2023.2.18f1-urp-webgl1
> [Automated workflow] upgrade-unity from 2023.2.10f1 to 2023.2.18f1-urp

- README.md
Added a link to my blog post explaining how web compression works, why Unity's default brotli compression needs odd server configurations and how to properly compress a game so that it can work on most (if not all) web servers.
> docs: add explanation on proper web compression

- Assets/UniversalRenderPipelineGlobalSettings.asset
- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/6000.0.2f1-urp-webgl2
* https://deml.io/experiments/unity-webgl/6000.0.2f1-urp-webgl1
> [Automated workflow] upgrade-unity from 6000.0.0f1 to 6000.0.2f1-urp

- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2022.3.32f1-webgl2
* https://deml.io/experiments/unity-webgl/2022.3.32f1-webgl1
> [Automated workflow] upgrade-unity from 2022.3.27f1 to 2022.3.32f1

- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/6000.0.8f1-webgl2
* https://deml.io/experiments/unity-webgl/6000.0.8f1-webgl1
> [Automated workflow] upgrade-unity from 6000.0.2f1 to 6000.0.8f1

- Assets/UniversalRenderPipelineGlobalSettings.asset
- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/6000.0.8f1-urp-webgl2
* https://deml.io/experiments/unity-webgl/6000.0.8f1-urp-webgl1
> [Automated workflow] upgrade-unity from 6000.0.2f1 to 6000.0.8f1-urp

- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2022.3.36f1-webgl2
* https://deml.io/experiments/unity-webgl/2022.3.36f1-webgl1
> [Automated workflow] upgrade-unity from 2022.3.32f1 to 2022.3.36f1

- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2022.3.36f1-urp-webgl2
* https://deml.io/experiments/unity-webgl/2022.3.36f1-urp-webgl1
> [Automated workflow] upgrade-unity from 2022.3.32f1 to 2022.3.36f1-urp

- Assets/UniversalRenderPipelineGlobalSettings.asset
- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/6000.0.9f1-urp-webgl2
* https://deml.io/experiments/unity-webgl/6000.0.9f1-urp-webgl1
> [Automated workflow] upgrade-unity from 6000.0.8f1 to 6000.0.9f1-urp

- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2021.3.38f1-webgl2
* https://deml.io/experiments/unity-webgl/2021.3.38f1-webgl1
> [Automated workflow] upgrade-unity from 2021.3.35f1 to 2021.3.38f1

- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2023.2.20f1-webgl2
* https://deml.io/experiments/unity-webgl/2023.2.20f1-webgl1
> [Automated workflow] upgrade-unity from 2023.2.18f1 to 2023.2.20f1

- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2022.3.42f1-urp-webgl2
* https://deml.io/experiments/unity-webgl/2022.3.42f1-urp-webgl1
> [Automated workflow] upgrade-unity from 2022.3.36f1 to 2022.3.42f1-urp

- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/6000.0.16f1-webgl2
* https://deml.io/experiments/unity-webgl/6000.0.16f1-webgl1
> [Automated workflow] upgrade-unity from 6000.0.9f1 to 6000.0.16f1

- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2021.3.45f1-urp-webgl2
* https://deml.io/experiments/unity-webgl/2021.3.45f1-urp-webgl1
> [Automated workflow] upgrade-unity from 2021.3.35f1 to 2021.3.45f1-urp

- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2022.3.50f1-urp-webgl2
* https://deml.io/experiments/unity-webgl/2022.3.50f1-urp-webgl1
> [Automated workflow] upgrade-unity from 2022.3.42f1 to 2022.3.50f1-urp

- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/6000.0.25f1-urp-webgl2
* https://deml.io/experiments/unity-webgl/6000.0.25f1-urp-webgl1
> [Automated workflow] upgrade-unity from 6000.0.23f1 to 6000.0.25f1-urp

- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/6000.0.25f1-webgl2
* https://deml.io/experiments/unity-webgl/6000.0.25f1-webgl1
> [Automated workflow] upgrade-unity from 6000.0.23f1 to 6000.0.25f1

- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2022.3.52f1-webgl2
* https://deml.io/experiments/unity-webgl/2022.3.52f1-webgl1
> [Automated workflow] upgrade-unity from 2022.3.50f1 to 2022.3.52f1

- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2022.3.52f1-urp-webgl2
* https://deml.io/experiments/unity-webgl/2022.3.52f1-urp-webgl1
> [Automated workflow] upgrade-unity from 2022.3.50f1 to 2022.3.52f1-urp

- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/6000.0.31f1-webgl2
* https://deml.io/experiments/unity-webgl/6000.0.31f1-webgl1
> [Automated workflow] upgrade-unity from 6000.0.27f1 to 6000.0.31f1

- Assets/UniversalRenderPipelineGlobalSettings.asset
- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/6000.0.32f1-urp-webgl2
* https://deml.io/experiments/unity-webgl/6000.0.32f1-urp-webgl1
> [Automated workflow] upgrade-unity from 6000.0.31f1 to 6000.0.32f1-urp

- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2022.3.56f1-urp-webgl2
* https://deml.io/experiments/unity-webgl/2022.3.56f1-urp-webgl1
> [Automated workflow] upgrade-unity from 2022.3.54f1-urp to 2022.3.56f1-urp

- Packages/manifest.json
- Packages/packages-lock.json
* https://deml.io/experiments/unity-webgl/2021.3.45f1-webgl2
* https://deml.io/experiments/unity-webgl/2021.3.45f1-webgl1
> [Automated workflow] upgrade-unity from 2021.3.45f1 to 2021.3.45f1

- Packages/manifest.json
- Packages/packages-lock.json
* https://deml.io/experiments/unity-webgl/2023.2.20f1-webgl2
* https://deml.io/experiments/unity-webgl/2023.2.20f1-webgl1
> [Automated workflow] upgrade-unity from 2023.2.20f1 to 2023.2.20f1

- Packages/manifest.json
- Packages/packages-lock.json
* https://deml.io/experiments/unity-webgl/2021.3.45f1-urp-webgl2
* https://deml.io/experiments/unity-webgl/2021.3.45f1-urp-webgl1
> [Automated workflow] upgrade-unity from 2021.3.45f1-urp to 2021.3.45f1-urp

- Packages/manifest.json
- Packages/packages-lock.json
* https://deml.io/experiments/unity-webgl/2023.2.20f1-urp-webgl2
* https://deml.io/experiments/unity-webgl/2023.2.20f1-urp-webgl1
> [Automated workflow] upgrade-unity from 2023.2.20f1-urp to 2023.2.20f1-urp

- Packages/manifest.json
- Packages/packages-lock.json
* https://deml.io/experiments/unity-webgl/2020.3.48f1-urp-webgl2
* https://deml.io/experiments/unity-webgl/2020.3.48f1-urp-webgl1
> [Automated workflow] upgrade-unity from 2020.3.48f1-urp to 2020.3.48f1-urp

- Packages/manifest.json
- Packages/packages-lock.json
* https://deml.io/experiments/unity-webgl/2023.1.20f1-urp-webgl2
* https://deml.io/experiments/unity-webgl/2023.1.20f1-urp-webgl1
> [Automated workflow] upgrade-unity from 2023.1.20f1-urp to 2023.1.20f1-urp

- Assets/UniversalRenderPipelineGlobalSettings.asset
- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/6000.0.40f1-urp-webgl2
* https://deml.io/experiments/unity-webgl/6000.0.40f1-urp-webgl1
> [Automated workflow] upgrade-unity from 6000.0.37f1-urp to 6000.0.40f1-urp

- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/6000.0.42f1-webgl2
* https://deml.io/experiments/unity-webgl/6000.0.42f1-webgl1
> [Automated workflow] upgrade-unity from 6000.0.40f1 to 6000.0.42f1

- Assets/UniversalRenderPipelineGlobalSettings.asset
- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/6000.0.48f1-urp-webgl2
* https://deml.io/experiments/unity-webgl/6000.0.48f1-urp-webgl1
> [Automated workflow] upgrade-unity from 6000.0.45f1-urp to 6000.0.48f1-urp

- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/6000.0.48f1-webgl2
* https://deml.io/experiments/unity-webgl/6000.0.48f1-webgl1
> [Automated workflow] upgrade-unity from 6000.0.45f1 to 6000.0.48f1

- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/2022.3.62f1-urp-webgl2
* https://deml.io/experiments/unity-webgl/2022.3.62f1-urp-webgl1
> [Automated workflow] upgrade-unity from 2022.3.61f1-urp to 2022.3.62f1-urp

- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/6000.1.7f1-webgl2
* https://deml.io/experiments/unity-webgl/6000.1.7f1-webgl1
> [Automated workflow] upgrade-unity from 6000.1.1f1 to 6000.1.7f1

- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
* https://deml.io/experiments/unity-webgl/6000.0.51f1-webgl2
* https://deml.io/experiments/unity-webgl/6000.0.51f1-webgl1
> [Automated workflow] upgrade-unity from 6000.0.48f1 to 6000.0.51f1
